---
schema: pegleg/CommonSoftwareConfig/v1
metadata:
  schema: metadata/Document/v1
  name: common-software-config
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  osh:
    region_name: 
  location:
    location_corridor: 
    location_name: 
    location_state: 
    location_country: 
    location_physical_location_id: 
    location_address: 
    location_zip: 
  infrastructure:
    sysadmin:
...
